-- ============================================================================
-- Script: Inserção de Dados - Guias CADASTUR (Parte 4 de 4)
-- Descrição: Quarta e última parte dos dados de guias de turismo
-- Registros: ~42 (restantes de 54.040 total)
-- Versão: 1.0
-- Data: 2025-09-06
-- ============================================================================

-- Usar o banco de dados
USE `trekko_db`;

-- Desabilitar verificações para melhor performance
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
SET AUTOCOMMIT = 0;

-- Início da transação
START TRANSACTION;

INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'FABIO RIBEIRO SOARES', '(63)99135-2074', 'fabiosoareslira0@gmail.com', '-', '27806965087', '2030-04-15 11:48:46.207000', 'Mateiros|Ponte Alta do Tocantins|São Félix do Tocantins', 'Guia Regional', 'Ecoturismo|Turismo Cultural|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'JOAO LUCAS AIRES PIMENTA', '(63)99200-7476', 'joaolucasairespimenta@gmail.com', 'joaolucas_pimenta', '-', '-', 'Ponte Alta do Tocantins|Mateiros|São Félix do Tocantins', 'Guia Regional', 'Turismo de Sol e Praia|Ecoturismo|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'EDUARDO TAKASHI KIKUCHI BUERES', '(63)99202-1399', 'kikuchibueres@gmail.com', '-', '-', '-', 'Ponte Alta do Tocantins', 'Guia Regional', 'Ecoturismo|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'RONAN PEREIRA RODRIGUES', '(63)99209-5491', 'ronanrodriguespereira10@gmail.com', '-', '27501403077', '2026-01-26 09:51:01.817000', '-', 'Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo de Aventura|Turismo de Sol e Praia', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'SANDNEY AIRES PEREIRA', '(63)99209-5491', 'sandneyaires12@gmail.com', '-', '27786664741', '2026-01-26 09:49:04.887000', '-', 'Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo de Aventura|Turismo de Sol e Praia', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'FABIO HENRIQUE DE SOUSA MELQUIADES', '(63)99209-6563', 'melquiadesfabiohenrique@gmail.com', '-', '27253063748', '2029-06-20 10:13:13.153000', 'Ponte Alta do Tocantins|Mateiros|Pindorama do Tocantins', 'Excursão Nacional - Brasil / América do Sul|Guia Regional', 'Turismo de Aventura|Turismo de Sol e Praia|Turismo Cultural', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'LEILSON FERREIRA LIMA', '(63)99213-6304', 'fabimbp@gmail.com', '-', '27769429450', '2026-06-18 09:45:47.867000', '-', 'Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo Rural|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'DOUGLAS DAMASCENO PIMENTA', '(63)99239-4719', 'douglasdpimenta@gmail.com', '-', '-', '-', 'Ponte Alta do Tocantins|Mateiros|São Félix do Tocantins', 'Guia Regional', 'Ecoturismo|Turismo Social', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'CARLOS EDUARDO ALVES SOUZA', '(63)99248-2159', 'carloseduardoalvessouza14@gmail.com', '-', '27618967760', '2026-02-02 13:39:57.663000', '-', 'Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo de Aventura|Turismo de Sol e Praia', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'MURIEL RODRIGUES NERES', '(63)99256-1246', 'murielr734@gmail.com', '.', '27454500072', '2029-05-09 09:24:44.430000', 'Mateiros|Pindorama do Tocantins|Ponte Alta do Tocantins', 'Guia Regional|Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo Cultural|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'EDUARDO SOUSA TAVARES', '(63)99261-8093', 'tavaressousaeduardo@gmail.com', '-', '-', '-', 'Mateiros|Ponte Alta do Tocantins|Pindorama do Tocantins', 'Guia Regional', 'Ecoturismo|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'KELLINY RIBEIRO SARAIVA', '(63)99264-1958', 'kekehfreitas2002@gmail.com', '-', '27566060936', '2026-03-10 09:31:44.137000', 'Ponte Alta do Tocantins', 'Guia Regional|Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo Cultural|Turismo de Sol e Praia', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'MARCIEL APOLINARIO DA SILVA', '(63)99279-8594', 'apolinariodasilvamarciel@gmail.com', '-', '27283902259', '2029-06-05 08:46:17.383000', 'Ponte Alta do Tocantins|Mateiros|São Félix do Tocantins', 'Guia Regional|Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo de Aventura|Turismo Cultural', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'JOSE GABRIEL GOMES SOARES', '(63)99285-5830', 'josegabrielgomessoares40@gmail.com', '-', '27661386963', '2029-05-23 10:02:43.257000', 'Mateiros|Ponte Alta do Tocantins|São Félix do Tocantins', 'Guia Regional|Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo Cultural|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'LARA FABYAN SOARES RIBEIRO', '(69)9105-7799', 'larafabyanribeiro@gmail.com', '-', '-', '-', '-', 'Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo Cultural|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Ponte Alta do Tocantins', 'MAGNO GOMES MELQUIADES', '084606618', 'gomesmagno643@Gmail.Com', '-', '27347654638', '2026-02-02 14:02:28.310000', '-', 'Excursão Nacional - Brasil / América do Sul', 'O(A) Guia de Turismo não é especialista em nenhum dos segmentos turísticos antes citados', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Porto Nacional', 'DEMOCRITO BRAGA DUAILIBE', '(63)3323-3014', 'DEMOCRITOBRAGA@HOTMAIL.COM', '-', '-', '-', 'Ponte Alta do Tocantins|Palmas|Mateiros', 'Guia Regional', 'O(A) Guia de Turismo não é especialista em nenhum dos segmentos turísticos antes citados', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Porto Nacional', 'JAIR JOSE DA SILVA', '(63)8475-2918', 'fernandagusttavo@hotmail.com', '-', '-', '-', 'Ponte Alta do Tocantins|Mateiros|São Félix do Tocantins', 'Guia Regional', 'O(A) Guia de Turismo não é especialista em nenhum dos segmentos turísticos antes citados', 1);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Porto Nacional', 'JONATAS RIBEIRO ARAUJO', '(63)98400-3637', 'jonatasxs5@gmail.com', '-', '-', '-', 'Mateiros|São Félix do Tocantins|Ponte Alta do Tocantins', 'Guia Regional', 'Ecoturismo|Turismo de Esporte|Turismo de Negócios e Eventos', 1);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Porto Nacional', 'LUCIANO MENEZES NUNES', '(63)98432-1703', 'luciano.menezesnunes@gmail.com', '-', '27363882104', '2029-04-15 12:09:55.363000', '-', 'Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo Cultural|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Porto Nacional', 'JEFFERSON LOPES BASTOS FILHO', '(63)98444-2077', 'jeffersonlopes.gabinete@gmail.com', '-', '27000596961', '2029-11-08 12:48:09.897000', 'Porto Nacional', 'Guia Regional|Excursão Nacional - Brasil / América do Sul', 'Turismo Cultural|Turismo Social|Ecoturismo', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Porto Nacional', 'MARIANA PIMENTA DE OLIVEIRA', '(63)98462-6430', 'mariana.ttur@gmail.com', '-', '27018534969', '2026-03-15 16:48:02.323000', '-', 'Excursão Nacional - Brasil / América do Sul', 'O(A) Guia de Turismo não é especialista em nenhum dos segmentos turísticos antes citados', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português|Italiano', 'Guia de Turismo', 'TO', 'Porto Nacional', 'VANESSA PAGANELLA SILVEIRA', '(63)98467-2143', 'VANESSAPAGANELLA@HOTMAIL.COM', '-', '23028113963', '2026-08-20 15:54:09.430000', 'Vacaria', 'Excursão Nacional - Brasil / América do Sul', 'O(A) Guia de Turismo não é especialista em nenhum dos segmentos turísticos antes citados', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Porto Nacional', 'BRENDO PEREIRA TURIBIO', '(63)98486-7113', 'brendoturibio92@gmail.com', '-', '-', '-', 'Ponte Alta do Tocantins|Mateiros|São Félix do Tocantins', 'Guia Regional', 'Ecoturismo|Turismo de Esporte|Turismo de Aventura', 1);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Porto Nacional', 'BRUNO PEREIRA TURIBIO', '(63)98511-2186', 'bruninhutu22@gmail.com', '-', '-', '-', 'Ponte Alta do Tocantins|São Félix do Tocantins|Mateiros', 'Guia Regional', 'Ecoturismo|Turismo de Esporte|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português|Inglês|Espanhol', 'Guia de Turismo', 'TO', 'Porto Nacional', 'ANDRE LUIZ JORGE RODRIGUES AGUIAR', '(63)99221-4742', 'offturismo@gmail.com', 'www.offturismo.com.br', '27377780640', '2028-05-05 12:28:59.613000', 'Mateiros|Palmas|Porto Nacional', 'Guia Regional|Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo Cultural|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Porto Nacional', 'SIRLENE RODRIGUES LIMA DUAILIBE', '(63)99232-0552', 'sirlenepedagoga99@gmail.com', '-', '-', '-', 'Palmas|Ponte Alta do Tocantins|Mateiros', 'Guia Regional', 'O(A) Guia de Turismo não é especialista em nenhum dos segmentos turísticos antes citados', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Rio da Conceição', 'THAYNARA THAYANE SOARES CARVALHO ALVES', '(63)99200-3317', 'thaynara.thayane1@gmail.com', '-', '-', '-', '-', 'Excursão Nacional - Brasil / América do Sul', 'Ecoturismo', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'São Félix do Tocantins', 'MARIA DE LOURDES BARBOSA PUGAS NETA', '(63)99271-4421', 'barbosanetinha2@gmai.com', '-', '27579781550', '2024-05-27 14:56:40.137000', '-', 'Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo Cultural|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'São Félix do Tocantins', 'LUCAS ROCHA XAVIER', '(63)99976-6568', 'lucasfb831@gmail.com', '-', '27930642785', '2024-06-10 11:25:53.553000', 'São Félix do Tocantins|Mateiros|Ponte Alta do Tocantins', 'Guia Regional|Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo de Aventura|Turismo Cultural', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'São Félix do Tocantins', 'AROLDO BENVINDO DE OLIVEIRA', '(63)99982-9024', 'virlandia_@hotmail.com', '-', '27898108111', '2030-02-20 11:36:37.093000', 'São Félix do Tocantins', 'Excursão Nacional - Brasil / América do Sul|Guia Regional', 'Ecoturismo|Turismo Cultural|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Silvanópolis', 'KAUAN SALES PIRES BARBOSA', '(63)99242-5743', 'meufilhoabidlima@gmail.com', '-', '-', '-', 'Mateiros|São Félix do Tocantins|Ponte Alta do Tocantins', 'Guia Regional|Atrativo Cultural|Atrativo Natural', 'Ecoturismo|Turismo de Aventura|Turismo Cultural', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Taquarussu do Tocantins', 'SARA REGINA COSTA SANTOS', '(11)97100-8473', 'sararegina@unitins.br', '-', '25177959290', '2030-02-19 11:40:12.237000', '-', 'Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo Cultural|Turismo de Sol e Praia', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Taquarussu do Tocantins', 'CARLOS MANUEL CARVALHO CARREIRA', '(63)98103-4655', 'carloscarr@gmail.com', '-', '27947663612', '2029-07-08 16:10:02.337000', 'Mateiros|Palmas|Natividade', 'Excursão Nacional - Brasil / América do Sul|Guia Regional', 'Ecoturismo|Turismo Cultural|Turismo Social', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Taquarussu do Tocantins', 'NEUZELINA BATISTA MENDES', '(63)99202-6212', 'neubatistamendes@gmail.com', '-', '27260090015', '2028-09-12 12:38:44.133000', '-', 'Excursão Nacional - Brasil / América do Sul', 'Ecoturismo|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Taquarussu do Tocantins', 'BRUNO PRESTES', '(63)99211-2318', 'prestes.biker@gmail.com', '-', '-', '-', 'Mateiros|Pindorama do Tocantins|Taquarussu do Tocantins', 'Guia Regional|Atrativo Cultural|Atrativo Natural', 'Turismo Cultural|Ecoturismo|Turismo de Esporte', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Taquarussu do Tocantins', 'DEYVID HENRIQUE INACIO DE OLIVEIRA', '(63)99221-8363', 'dinaciodeoliveira@gmail.com', '-', '27420692379', '2028-11-07 09:07:20.693000', 'Palmas', 'Excursão Nacional - Brasil / América do Sul|Guia Regional', 'Turismo de Aventura|Ecoturismo|Turismo Cultural', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Taquarussu do Tocantins', 'VALDILEIA GOMES DA SILVA', '(63)99253-4755', 'val-gsilva@hotmail.com', '-', '27907004225', '2028-05-30 11:28:03.277000', 'Palmas|Mateiros|São Félix do Tocantins', 'Excursão Nacional - Brasil / América do Sul|Guia Regional|Atrativo Natural', 'Turismo de Sol e Praia|Ecoturismo|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Taquarussu do Tocantins', 'SERGIO RICARDO MORETTI', '(63)99270-4022', 'moretrex@gmail.com', '-', '27255544779', '2029-09-03 12:11:55.763000', 'Palmas', 'Excursão Nacional - Brasil / América do Sul|Guia Regional', 'Ecoturismo|Turismo de Aventura|Turismo Cultural', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Taquarussu do Tocantins', 'NEUSIVAL BATISTA MENDES', '(63)99281-3740', 'neusivalmendes@gmail.com', '-', '27128380073', '2029-08-20 08:42:14.843000', 'Palmas', 'Excursão Nacional - Brasil / América do Sul|Guia Regional', 'Ecoturismo|Turismo de Aventura', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('-', 'Guia de Turismo', 'TO', 'Xambioá', 'IGOR DE SOUSA SANDES', '(63)99125-1805', 'igorsandes63@gmail.com', '-', '-', '-', 'Xambioá|Araguanã', 'Guia Regional', 'Ecoturismo|Turismo Rural|Turismo de Pesca', 0);
INSERT INTO `guias_cadastur` (`idiomas`, `atividade_turística`, `uf`, `município`, `nome_completo`, `telefone_comercial`, `email_comercial`, `website`, `número_do_certificado`, `validade_do_certificado`, `município_de_atuação`, `categorias`, `segmentos`, `guia_motorista`) VALUES ('Português', 'Guia de Turismo', 'TO', 'Xambioá', 'LUIS ALVES RIBEIRO', '(63)99279-9010', 'luisalvesribeiro@live.com', '-', '-', '-', 'Xambioá', 'Guia Regional', 'Turismo Cultural', 0);

-- Finalizar transação
COMMIT;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
SET AUTOCOMMIT = 1;
